import { ChurchData } from '../types';

// Dynamically set future event date 14 days from now at 19:30
const futureDate = new Date();
futureDate.setDate(futureDate.getDate() + 14);
futureDate.setHours(19, 30, 0, 0);

export const defaultChurchData: ChurchData = {
  hero: {
    badge: 'Atividade em Destaque',
    title: 'Conferência de Fé: O Despertar da Promessa',
    subtitle: 'Uma convocação profética para viver o sobrenatural e restaurar o propósito divino em todas as famílias.',
    eventDate: futureDate.toISOString(),
    location: 'Auditório Principal — Catedral de Amor e Fé',
    locationDetails: 'Av. das Nações, 1200 — Jardins da Aliança',
    preacher: 'Bispo Samuel Oliveira',
    preacherRole: 'Pastor Sênior & Presidente',
    quote: 'Uma jornada profunda de renovação espiritual e comunhão com a palavra revelada para toda a família.',
    description: 'Serão 3 dias inesquecíveis com adoração genuína, ministração profunda das Escrituras e manifestação visível da graça de Deus. Traga sua família e participe deste divisor de águas.',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    ctaText: 'Garantir Inscrição Gratuita',
    secondaryCtaText: 'Ver Localização',
  },
  pillars: [
    {
      id: 'pillar-1',
      number: '01',
      title: 'Louvor & Adoração',
      description: 'Música que eleva a alma, quebra cadeias e conecta corações apaixonados ao Santo dos Santos.',
      iconName: 'Music',
      image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=600',
    },
    {
      id: 'pillar-2',
      number: '02',
      title: 'Palavra Revelada',
      description: 'Ensinamentos bíblicos profundos, práticos e transformadores para guiar a vida cotidiana.',
      iconName: 'BookOpen',
      image: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&q=80&w=600',
    },
    {
      id: 'pillar-3',
      number: '03',
      title: 'Comunhão & Família',
      description: 'Um espaço seguro e acolhedor para crescer, edificar lares e compartilhar o amor fraterno.',
      iconName: 'Users',
      image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=600',
    },
    {
      id: 'pillar-4',
      number: '04',
      title: 'Milagres & Oração',
      description: 'Acreditamos no poder irrestrito da fé e da intercessão contínua para transformar qualquer realidade.',
      iconName: 'Flame',
      image: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?auto=format&fit=crop&q=80&w=600',
    },
  ],
  photos: [
    {
      id: 'photo-1',
      title: 'Noite de Avivamento e Louvor',
      category: 'Louvor',
      url: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-10',
      featured: true,
    },
    {
      id: 'photo-2',
      title: 'Ministração da Palavra de Fé',
      category: 'Palavra',
      url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-12',
      featured: true,
    },
    {
      id: 'photo-3',
      title: 'Conferência de Jovens Radicais',
      category: 'Juventude',
      url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-14',
      featured: true,
    },
    {
      id: 'photo-4',
      title: 'Celebração de Batismo nas Águas',
      category: 'Comunhão',
      url: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-15',
      featured: false,
    },
    {
      id: 'photo-5',
      title: 'Culto da Família Abençoada',
      category: 'Famílias',
      url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-16',
      featured: true,
    },
    {
      id: 'photo-6',
      title: 'Momento Profundo de Clamor e Intercessão',
      category: 'Palavra',
      url: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-17',
      featured: false,
    },
    {
      id: 'photo-7',
      title: 'Orquestra e Coral Catedral',
      category: 'Louvor',
      url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-18',
      featured: false,
    },
    {
      id: 'photo-8',
      title: 'Acampamento & Retiro Espiritual',
      category: 'Juventude',
      url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=1200',
      date: '2026-08-19',
      featured: false,
    },
  ],
  photoCategories: ['Todos', 'Louvor', 'Palavra', 'Juventude', 'Comunhão', 'Famílias'],
  videos: [
    {
      id: 'vid-1',
      title: 'Culto Solene: Rompendo Limites pela Fé',
      youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      duration: '1h 35m',
      date: 'Domingo Passado',
      speaker: 'Bispo Samuel Oliveira',
      isFeatured: true,
      thumbnailUrl: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=1200',
    },
    {
      id: 'vid-2',
      title: 'Noite de Louvor & Adoração Profética',
      youtubeUrl: 'https://www.youtube.com/watch?v=kXYiU_JCYtU',
      duration: '48m',
      date: 'Quarta-feira',
      speaker: 'Ministério de Louvor Catedral',
      isFeatured: false,
      thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&q=80&w=800',
    },
    {
      id: 'vid-3',
      title: 'Princípios Inegociáveis da Fé Cristã',
      youtubeUrl: 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ',
      duration: '1h 12m',
      date: '03 de Agosto',
      speaker: 'Pastora Helena Ramos',
      isFeatured: false,
      thumbnailUrl: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?auto=format&fit=crop&q=80&w=800',
    },
  ],
  regularServices: [
    {
      id: 'svc-1',
      day: 'Domingos',
      time: '09:00',
      title: 'Culto de Celebração Matinal',
      description: 'Ceia do Senhor, estudo bíblico e escola de líderes para toda a família.',
      location: 'Nave Principal & Transmissão Ao Vivo',
    },
    {
      id: 'svc-2',
      day: 'Domingos',
      time: '18:00',
      title: 'Grande Culto da Família & Avivamento',
      description: 'Ministração impactante, louvor contemporâneo e acolhimento pastoral.',
      location: 'Nave Principal',
    },
    {
      id: 'svc-3',
      day: 'Quartas-feiras',
      time: '19:30',
      title: 'Culto da Palavra & Clamor pelos Lares',
      description: 'Ensino expositivo das Escrituras e momento especial de oração por curas.',
      location: 'Auditório Anexo 1',
    },
    {
      id: 'svc-4',
      day: 'Sábados',
      time: '19:00',
      title: 'Juventude Catedral (Conexão Jovem)',
      description: 'Adoração vibrante, comunhão, grupos de conexão e mentoria cristã.',
      location: 'Espaço Jovem',
    },
  ],
  upcomingEvents: [
    {
      id: 'event-1',
      title: 'Conferência de Fé: O Despertar da Promessa',
      date: '2026-09-15',
      time: '19:30',
      location: 'Auditório Principal — Catedral de Amor e Fé',
      speaker: 'Bispo Samuel Oliveira & Convidados',
      totalSeats: 1200,
      seatsLeft: 342,
      image: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=800',
      description: 'Uma convocação profética para viver o sobrenatural e restaurar o propósito divino.',
      registrationOpen: true,
      tag: 'Principal',
    },
    {
      id: 'event-2',
      title: 'Seminário de Casais: Blindando o Matrimônio',
      date: '2026-09-26',
      time: '18:30',
      location: 'Salão Nobre da Catedral',
      speaker: 'Pr. Carlos e Pra. Mariana Tavares',
      totalSeats: 250,
      seatsLeft: 64,
      image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&q=80&w=800',
      description: 'Princípios bíblicos para fortalecer o amor, a comunicação e as finanças do casal.',
      registrationOpen: true,
      tag: 'Famílias',
    },
    {
      id: 'event-3',
      title: 'Vigília da Vitória: Noite de Clamor e Resposta',
      date: '2026-10-02',
      time: '22:00',
      location: 'Nave Central',
      speaker: 'Corpo Pastoral Catedral',
      totalSeats: 1500,
      seatsLeft: 890,
      image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=800',
      description: 'Sete horas contínuas de oração, louvor ininterrupto e imposição de mãos.',
      registrationOpen: true,
      tag: 'Oração',
    },
  ],
  testimonials: [
    {
      id: 'test-1',
      name: 'Dr. Roberto Silveira',
      role: 'Membro há 8 anos',
      quote: 'Encontrei na Catedral um verdadeiro porto seguro de amor e restauração para minha família quando mais precisávamos.',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
      date: 'Julho de 2026',
    },
    {
      id: 'test-2',
      name: 'Juliana Mendes',
      role: 'Líder de Jovens',
      quote: 'O ambiente de adoração genuína e o discipulado bíblico me ensinaram a caminhar com firmeza e propósito.',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300',
      date: 'Agosto de 2026',
    },
    {
      id: 'test-3',
      name: 'Marcos & Patrícia Lima',
      role: 'Ministério de Famílias',
      quote: 'Nossos filhos cresceram aqui e hoje servem a Deus com alegria. É uma igreja que cuida de pessoas com excelência.',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
      date: 'Junho de 2026',
    },
  ],
  contact: {
    whatsappNumber: '+5511999998888',
    defaultMessage: 'Olá! Gostaria de saber mais sobre os cultos e atividades da Catedral de Amor e Fé.',
    phone: '(11) 3456-7890',
    email: 'contato@catedraldeamorefe.org.br',
    address: 'Av. das Nações, 1200 — Jardins da Aliança',
    cityState: 'São Paulo, SP — CEP 01400-000',
    googleMapsUrl: 'https://maps.google.com/?q=Av.+das+Nações+1200',
    socialLinks: {
      youtube: 'https://youtube.com/@catedraldeamorefe',
      instagram: 'https://instagram.com/catedraldeamorefe',
      facebook: 'https://facebook.com/catedraldeamorefe',
      spotify: 'https://spotify.com',
      whatsappChannel: 'https://whatsapp.com/channel/catedral',
    },
  },
  stats: [
    { label: 'Membros Ativos', value: '4.500+' },
    { label: 'Células nos Lares', value: '180' },
    { label: 'Projetos Sociais', value: '14' },
    { label: 'Anos de História', value: '28 Anos' },
  ],
  lastUpdated: new Date().toISOString(),
};
